### ISSUE TITLE
Can't go back to original firmware

### ISSUE THREAD

**Issue by httpsTeabagexe** [hzyitc/openwrt-redmi-ax3000#87]
Following the guide on [openWRT docs page](https://openwrt.org/docs/guide-user/installation/generic.uninstall) the following error appears while attempting to flash original firmware:
![image](https://github.com/user-attachments/assets/43790181-f968-4851-9f00-dd0addb5a570)

**An attempt to load firmware through web GUI leads to router rebooting and nothing else**

![image](https://github.com/user-attachments/assets/55362802-7a5a-4e13-b37d-b7070571ccc8)
![image](https://github.com/user-attachments/assets/f1fd29ba-c190-4d1d-aaae-bd332d3ffee0)

After reboot openwrt's login page opens
![image](https://github.com/user-attachments/assets/36b17f67-ce70-4432-a65d-cc445f8c0796)

**Comment by fecent** [comment]
You can use `cat /sys/class/ubi/ubi*/mtd_num` to view the running partition

If return 18, use a value of `1` go back to xiaomi firmware, otherwise, use a value of `0`
`fw_setenv  flag_last_success 1`
`fw_setenv flag_boot_rootfs 1`
`reboot`

Go back to openwrt: 
`nvram set flag_last_success=0`
`nvram set flag_boot_rootfs=0`
`nvram commit`
`reboot`

You can easily switch between two systems

**Comment by httpsTeabagexe** [comment]
@fecent Thanks for the suggestion! The partitions indeed switch between each other

The problem is that i somehow installed openwrt on both 18 and 19 partitions

**Comment by fecent** [comment]
> @fecent Thanks for the suggestion! The partitions indeed switch between each other
> 
> The problem is that i somehow installed openwrt on both 18 and 19 partitions

You can only use the MIWIFIRepairTool in Readme to flash back the Xiaomi firmware and then reinstall Openwrt in another partition. It is recommended to follow Rreadme to install Openwrt in another partition so that you can keep both systems

Note: Using MIWIFIRepairTool will completely erase two partitions and write Xiaomi firmware
